import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
import FormbricksProvider from "./formbricks"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "MotionScope",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <FormbricksProvider />
      <body className={inter.className}>
        <Navbar />
        <main> {children}</main>
      </body>
    </html>
  );
}
