import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { UserProvider } from "@auth0/nextjs-auth0/client";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "MotionScope",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <UserProvider>
        <body className={inter.className}>
          <main>
            <h1>Motionscope</h1>
            <h2>Where the mind meets body</h2>
            {children}</main>
        </body>
      </UserProvider>
    </html>
  );
}
